
% Raytrix R29 normalized resolution using the SPC model
clear all;

pitch = 171;        % um
n_x = 31;
pixel_size = pitch/n_x;

load('StitchedResDistR29.mat');% This file is generated by StitchedResDistR29.m
figure;
hold on
plot(z_plane,pixel_size./res, 'r');
title('Spatial resolution profile through depth, normalized to the image sensor resolution, using the SPC-model-based approach');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Normalized resolution for a plenoptic camera with three-focal length microlens array structure, using the analytical approach
clear all

f1 = 1000*input('Focal length of the type I lenslet, f1(mm): ');              % in um
f2 = 1000*input('Focal length of the type I lenslet, f2(mm): ');              % in um
f3 = 1000*input('Focal length of the type I lenslet, f3(mm): ');              % in um
g = 1000*input('The gap between the sensor and the lenslet array, g(mm): ');  % in um

pitch = 1000*input('Pitch size of the lenslet, p(mm): ');                     % in um
if isempty(pitch)
    pitch = 171;
end

n_x = input('Number of pixels in a row behind one lenslet: ');
if isempty(n_x)
    n_x = 31;
end

z_plane = input('The depth range of interest in the form of depth1:depth2, e.g. -100000:30000 (in um): ');
if isempty(z_plane)
    z_plane = -100000:30000;
end

s = pitch.*(g.*((1/f1)-(1./(z_plane)))-1);
ERR1 = (pitch/n_x)./max(abs(s),(pitch/n_x)) .* abs(g./(z_plane)); % All lenslets are considered to be of type I
% figure;
% hold on
% plot(z_plane-g,ELRR1, 'r');

s = pitch.*(g.*((1/f2)-(1./(z_plane)))-1);
ERR2 = (pitch/n_x)./max(abs(s),(pitch/n_x)) .* abs(g./(z_plane)); % All lenslets are considered to be of type II
% figure;
% hold on
% plot(z_plane-g,ELRR2, 'g');

s = pitch.*(g.*((1/f3)-(1./(z_plane)))-1);
ERR3 = (pitch/n_x)./max(abs(s),(pitch/n_x)) .* abs(g./(z_plane)); % All lenslets are considered to be of type III
% figure;
% hold on
% plot(z_plane-g,ELRR3, 'b');

ELRR = max(ERR1,ERR2);
ELRR = max(ELRR,ERR3);
% figure;
hold on
plot(z_plane,ELRR, 'm');

title('Spatial resolution profile through depth, normalized to the image sensor resolution, using the analytical approach');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%